# CMake generated Testfile for 
# Source directory: /home/ubt/catkin_ws/src
# Build directory: /home/ubt/catkin_ws/build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("gtest")
subdirs("hector_slam/hector_geotiff_launch")
subdirs("hector_slam/hector_slam")
subdirs("hector_slam/hector_slam_launch")
subdirs("rosserial/rosserial")
subdirs("rosserial/rosserial_arduino")
subdirs("rosserial/rosserial_chibios")
subdirs("rosserial/rosserial_mbed")
subdirs("rosserial/rosserial_msgs")
subdirs("rosserial/rosserial_python")
subdirs("rosserial/rosserial_tivac")
subdirs("rosserial/rosserial_vex_cortex")
subdirs("rosserial/rosserial_vex_v5")
subdirs("rosserial/rosserial_xbee")
subdirs("rosserial/rosserial_client")
subdirs("hector_slam/hector_map_tools")
subdirs("hector_slam/hector_nav_msgs")
subdirs("teb_local_planner_tutorials")
subdirs("bibot")
subdirs("bibot_communication")
subdirs("bibot_description")
subdirs("bibot_navigation")
subdirs("bibot_web")
subdirs("hector_slam/hector_geotiff")
subdirs("hector_slam/hector_geotiff_plugins")
subdirs("hector_slam/hector_marker_drawing")
subdirs("rosserial/rosserial_server")
subdirs("hector_slam/hector_compressed_map_transport")
subdirs("rplidar_ros")
subdirs("als_ros/src/als_ros")
subdirs("differential-drive")
subdirs("hector_slam/hector_imu_attitude_to_tf")
subdirs("hector_slam/hector_imu_tools")
subdirs("hector_slam/hector_map_server")
subdirs("hector_slam/hector_trajectory_server")
subdirs("rosserial/rosserial_embeddedlinux")
subdirs("rosserial/rosserial_test")
subdirs("rosserial/rosserial_windows")
subdirs("hector_slam/hector_mapping")
