set(_CATKIN_CURRENT_PACKAGE "mcl_ros")
set(mcl_ros_VERSION "0.0.0")
set(mcl_ros_MAINTAINER "akai <akai@todo.todo>")
set(mcl_ros_PACKAGE_FORMAT "2")
set(mcl_ros_BUILD_DEPENDS "cv_bridge" "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(mcl_ros_BUILD_EXPORT_DEPENDS "cv_bridge" "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(mcl_ros_BUILDTOOL_DEPENDS "catkin")
set(mcl_ros_BUILDTOOL_EXPORT_DEPENDS )
set(mcl_ros_EXEC_DEPENDS "cv_bridge" "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(mcl_ros_RUN_DEPENDS "cv_bridge" "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(mcl_ros_TEST_DEPENDS )
set(mcl_ros_DOC_DEPENDS )
set(mcl_ros_URL_WEBSITE "")
set(mcl_ros_URL_BUGTRACKER "")
set(mcl_ros_URL_REPOSITORY "")
set(mcl_ros_DEPRECATED "")