set(_CATKIN_CURRENT_PACKAGE "bibot_communication")
set(bibot_communication_VERSION "0.0.0")
set(bibot_communication_MAINTAINER "ubt <ubt@todo.todo>")
set(bibot_communication_PACKAGE_FORMAT "2")
set(bibot_communication_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_communication_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_communication_BUILDTOOL_DEPENDS "catkin")
set(bibot_communication_BUILDTOOL_EXPORT_DEPENDS )
set(bibot_communication_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_communication_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_communication_TEST_DEPENDS )
set(bibot_communication_DOC_DEPENDS )
set(bibot_communication_URL_WEBSITE "")
set(bibot_communication_URL_BUGTRACKER "")
set(bibot_communication_URL_REPOSITORY "")
set(bibot_communication_DEPRECATED "")