set(_CATKIN_CURRENT_PACKAGE "bibot_web")
set(bibot_web_VERSION "0.0.0")
set(bibot_web_MAINTAINER "ubt <ubt@todo.todo>")
set(bibot_web_PACKAGE_FORMAT "2")
set(bibot_web_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_web_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_web_BUILDTOOL_DEPENDS "catkin")
set(bibot_web_BUILDTOOL_EXPORT_DEPENDS )
set(bibot_web_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_web_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_web_TEST_DEPENDS )
set(bibot_web_DOC_DEPENDS )
set(bibot_web_URL_WEBSITE "")
set(bibot_web_URL_BUGTRACKER "")
set(bibot_web_URL_REPOSITORY "")
set(bibot_web_DEPRECATED "")