set(_CATKIN_CURRENT_PACKAGE "bibot_description")
set(bibot_description_VERSION "0.0.0")
set(bibot_description_MAINTAINER "ubt <ubt@todo.todo>")
set(bibot_description_PACKAGE_FORMAT "2")
set(bibot_description_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_description_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_description_BUILDTOOL_DEPENDS "catkin")
set(bibot_description_BUILDTOOL_EXPORT_DEPENDS )
set(bibot_description_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_description_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_description_TEST_DEPENDS )
set(bibot_description_DOC_DEPENDS )
set(bibot_description_URL_WEBSITE "")
set(bibot_description_URL_BUGTRACKER "")
set(bibot_description_URL_REPOSITORY "")
set(bibot_description_DEPRECATED "")