set(_CATKIN_CURRENT_PACKAGE "bibot")
set(bibot_VERSION "0.0.0")
set(bibot_MAINTAINER "ubt <ubt@todo.todo>")
set(bibot_PACKAGE_FORMAT "2")
set(bibot_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_BUILDTOOL_DEPENDS "catkin")
set(bibot_BUILDTOOL_EXPORT_DEPENDS )
set(bibot_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_TEST_DEPENDS )
set(bibot_DOC_DEPENDS )
set(bibot_URL_WEBSITE "")
set(bibot_URL_BUGTRACKER "")
set(bibot_URL_REPOSITORY "")
set(bibot_DEPRECATED "")