set(_CATKIN_CURRENT_PACKAGE "als_ros")
set(als_ros_VERSION "0.0.0")
set(als_ros_MAINTAINER "akai <n.akai.goo@gmail.com>")
set(als_ros_PACKAGE_FORMAT "2")
set(als_ros_BUILD_DEPENDS "cv_bridge" "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(als_ros_BUILD_EXPORT_DEPENDS "cv_bridge" "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(als_ros_BUILDTOOL_DEPENDS "catkin")
set(als_ros_BUILDTOOL_EXPORT_DEPENDS )
set(als_ros_EXEC_DEPENDS "cv_bridge" "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(als_ros_RUN_DEPENDS "cv_bridge" "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(als_ros_TEST_DEPENDS )
set(als_ros_DOC_DEPENDS )
set(als_ros_URL_WEBSITE "")
set(als_ros_URL_BUGTRACKER "")
set(als_ros_URL_REPOSITORY "")
set(als_ros_DEPRECATED "")