set(_CATKIN_CURRENT_PACKAGE "bibot_navigation")
set(bibot_navigation_VERSION "0.0.0")
set(bibot_navigation_MAINTAINER "ubt <ubt@todo.todo>")
set(bibot_navigation_PACKAGE_FORMAT "2")
set(bibot_navigation_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_navigation_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_navigation_BUILDTOOL_DEPENDS "catkin")
set(bibot_navigation_BUILDTOOL_EXPORT_DEPENDS )
set(bibot_navigation_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_navigation_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(bibot_navigation_TEST_DEPENDS )
set(bibot_navigation_DOC_DEPENDS )
set(bibot_navigation_URL_WEBSITE "")
set(bibot_navigation_URL_BUGTRACKER "")
set(bibot_navigation_URL_REPOSITORY "")
set(bibot_navigation_DEPRECATED "")